name: LifeX
version: 1.0.0
main: me.amar.lifex.LifeX
api-version: 1.13
commands:
  life:
    description: The main LifeX command.
    aliases: [l]
  useless:
    description: does nothing
  settab:
    description: does someting
    aliases: [ht]