name: XLife
version: 1.0.0
main: me.amar.xlife.xlife.XLife
api-version: 1.13
commands:
  reset:
    description: reset the hearts of a player.
  set:
    description: set the hearts of a player.
  rlconfig:
    description: reloads config of xlife
  useless:
    description: does nothing